version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backintimeshopdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    env_file:
      - .env