version: '3.8'

services:
  app:
    image: dark24kot776/backintimeshopapi:1.4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:alpine
    container_name: ${DB_NAME}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env