CREATE TABLE IF NOT EXISTS users(
id BIGSERIAL PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(100) NOT NULL CHECK(LENGTH(password)>=8),
active_token VARCHAR UNIQUE,
last_login_date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
last_updated_date DATE NOT NULL,
created_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS roles(
id BIGSERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS user_roles (
id BIGSERIAL PRIMARY KEY,
user_id BIGINT NOT NULL,
role_id BIGINT NOT NULL,
CONSTRAINT user_role_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
CONSTRAINT role_user_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

INSERT INTO roles (name) VALUES ('ROLE_ADMIN'),('ROLE_TESTER'), ('ROLE_USER');
